name: Benchmark mac-os criterion 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  criterion-templates:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown   

      - name: Install protoc
        uses: taiki-e/install-action@v1
        with:
          tool: protoc

      - name: install jq
        run: brew install jq   

      - name: Install cargo-criterion
        run: cargo install cargo-criterion

      - name: Install criterion-table
        run: cargo install criterion-table

      - name: mkdir
        run: mkdir criterion-template-results

      - name: build engine
        run: |
          cd sightglass/engines/wasmtime && \
          rustc build.rs && \
          ./build 
      - name: ls -la
        run: |
          ls -la
      - name: cd sightglass && ls -la
        run: |
          cd sightglass && ls -la
      - name: build benchmarks
        run: |
          cd sightglass && ./benchmarks/build-all.sh
      - name: build benchmarks
        run: |
          cd sightglass && ./benchmarks/build-all.sh

      - name: Run benchmarks
        run: |
          cargo criterion \
          --message-format json \
          | jq -r 'select(has("id"))| .id|=(gsub("\\s";"_")| sub("::";"/") | ascii_downcase)' \
          | criterion-table \
          > criterion-template-results/BENCHMARKS-ARKWORKS-WASMTIME.md
      
      - name: Publish criterion results on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./criterion-template-results
          keep_files: true
          github_token: ${{ secrets.BENCH_RESULTS_ACCESS_TOKEN }}
          

     